/* eslint-disable @typescript-eslint/no-var-requires */
export const BG = require('./default-background/default-background.png')
export const LOGO = require('./logo.png')
export const paymentSuccessIllu = require('./payment-success/payment-success.png')
export const GameImageBackground = require('./game-bg/game-img-bg.png')
export const CardHofBG = require('./card-hof-bg/card-hof-bg.png')
export const rackIllu = require('./rack/rack.png')
export const smokeIntermediateIllu = require('./smoke-intermediate-bg/smoke-intermediate-bg.png')
export const smokeLegendIllu = require('./smoke-legend-bg/smoke-legend-bg.png')
export const smokeMasterIllu = require('./smoke-master-bg/smoke-master-bg.png')
export const smokeNoviceIllu = require('./smoke-novice-bg/smoke-novice-bg.png')
export const neonCircleIllu = require('./neon-circle/neon-circle.png')
export const getAwardIllu = require('./get-award/get-award.png')
